os: linux
language: node_js

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

node_js:
  - "8"

# skip fetching the git-lfs files
git:
  lfs_skip_smudge: true

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn

# no test task exist, yet, theirfore we test some other tasks (e.g. build)
script:
  - yarn lint
  - yarn build

# after_success:
#   - find ./dist -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://sftp.hackerstolz.de/httpd.www/climathon --user ${SFTP_USER}:${SFTP_PASSWORD} \;

# after_success:
#   - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#   - curl --ftp-create-dirs
#         -T ./dist
#         --key /tmp/sftp_rsa
#         sftp://${SFTP_USER}:${SFTP_PASSWORD}@sftp.hackerstolz.de/httpd.www/climathon